src/leo-client-app/package-lock.json
src/leo-client-app/package.json
src/leo-client-app/src/app/page.tsx
src/leo-client-app/src/components/SatelliteInfo.tsx
src/leo-client-app/yarn.lock
src/leo-server-app/package-lock.json
src/leo-server-app/package.json
src/leo-server-app/src/server.ts
src/leo-server-app/yarn.lock

Added API endpoint to get relevant tracking data via satellite.js library (https://github.com/shashwatak/satellite-js)
Created `SatelliteInfo` React (client) component 
Added `SatelliteInfo` component to front-end as POC
Added concurrently package to run client and back-end server with `npm run all`

Added NEUDOSE Satellite Tracking Information

---

src/leo-client-app/src/app/page.tsx
src/leo-client-app/src/components/FuturePasses.tsx
src/leo-server-app/src/server.ts

Added API endpoint to calculate overpass times for the next 7 days
Created `FuturePasses` React (client) component
Added `FuturePasses` component to front-end as POC
Created `getSatelliteInfo` function for reusability
Edited TLE and GS GD information for accuracy

Added Satellite Overpass Calculations

---

src/leo-server-app/src/routes/log.ts
src/leo-server-app/src/routes/satellite.ts
src/leo-server-app/src/routes/schedule.ts

Changed get request endpoints in server repo to reference query instead of body

Enhancement: Change get request param

---

src/docs/SatelliteInfo.md

Added satellite documentation, including how satellites are tracked, and how data is obtained

Added satellite documentation

---

src/leo-server-app/package-lock.json
src/leo-server-app/package.json
src/leo-server-app/src/routes/satellite.ts
src/leo-server-app/src/types/satellites.ts
src/leo-server-app/yarn.lock

Added API call from Space-Track for TLE information
Changes allows for modular TLE swapping based off NORAD identifier, with more accurate, up-to-date TLE information

Added API call from Space-Track for TLE information

---

.github/workflows/node-server.js.yml
.gitignore
src/leo-server-app/babel.config.js
src/leo-server-app/jest.config.ts
src/leo-server-app/package-lock.json
src/leo-server-app/package.json
src/leo-server-app/src/routes/satellite.ts
src/leo-server-app/src/server.ts
src/leo-server-app/src/tests/satellite.test.ts
src/leo-server-app/tsconfig.json
src/leo-server-app/yarn.lock

Added Jest testing from #110 into github actions

Added Jest testing into github actions

---

src/leo-server-app/src/models/command.ts
src/leo-server-app/src/models/log.ts
src/leo-server-app/src/models/satellite.ts
src/leo-server-app/src/models/schedule.ts
src/leo-server-app/src/models/user.ts
src/leo-server-app/src/routes/schedule.ts
src/leo-server-app/src/types/command.ts
src/leo-server-app/src/types/schedule.ts

Updated command, schedule, satellite and user schemas as per issues #117 and #113

Feature: Updated MongoDB Schemas

---

src/leo-server-app/jest.config.ts
src/leo-server-app/package-lock.json
src/leo-server-app/package.json
src/leo-server-app/src/app.ts
src/leo-server-app/src/database/database.ts
src/leo-server-app/src/models/command.ts
src/leo-server-app/src/models/satellite.ts
src/leo-server-app/src/models/schedule.ts
src/leo-server-app/src/models/user.ts
src/leo-server-app/src/routes/schedule.ts
src/leo-server-app/src/routes/user.ts
src/leo-server-app/src/server.ts
src/leo-server-app/src/tests/satellite.test.ts
src/leo-server-app/src/tests/schedule.test.ts
src/leo-server-app/yarn.lock

Created an endpoint to update an existing scheduled command sequence
- Set up mongodb mock server when performing jest unit tests
- Added a test to verify the functionality of endpoint
- The other test cases have been described in comments, need to do in separate pr
Related issues: #119

Feature: Added Endpoint to update scheduled command sequence

---

src/leo-server-app/package-lock.json
src/leo-server-app/package.json
src/leo-server-app/yarn.lock

Installed and integrated cross-env package
Test:
- Run leo-server-app repo by navigating to directory and running "npm run start:dev", it should be working

Feature: Cross-env for Cross Compatiability

---

src/leo-server-app/src/routes/schedule.ts
src/leo-server-app/src/tests/schedule.test.ts

Created an endpoint to remove a scheduled command sequence as part of /schedule route

Feature: Remove Scheduled Command Endpoint 

---

src/leo-server-app/src/routes/schedule.ts
src/leo-server-app/src/tests/schedule.test.ts

Changes made:
- Created an endpoint to fetch commands by a schedule
- Created an endpoint to fetch schedules by a satellite
Testing:
- GET commands by schedule: /schedule/getCommandsBySchedule
- GET schedules by a satellite: /schedule/getSchedulesBySatellite

Feature: GET Schedule Endpoints

---

src/leo-server-app/src/routes/satellite.ts
src/leo-server-app/yarn.lock

As per external stakeholder requests, AOS should be 0 degrees, and not 10.

Corrected Definition for Minimum Elevation

---

src/leo-client-app/src/components/DetailedDisplay.tsx

As per stakeholder requests, styling added to entry and exit points to indicate direction in polar plots

Added Entry and Exit styling for Polar Plot Diagram

---

src/leo-server-app/src/models/satellite.ts
src/leo-server-app/src/routes/satellite.ts
src/leo-server-app/src/routes/user.ts

Changes made:
- Fixed importing satellite and user models in routes/satellite.ts
- Updated Satellite export to SatelliteModel

Fix: Importing Models

---

src/docs/api/Satellite.md
src/leo-client-app/src/components/SatelliteTLE.tsx
src/leo-client-app/src/pages/satellite-passes/index.tsx
src/leo-server-app/src/routes/satellite.ts
src/leo-server-app/src/tests/satellite.test.ts

Demo:
https://github.com/RishiVaya/Lower_Earth_Orbiters/assets/35006641/1f7e4309-0427-4b7c-8d9d-4453f9a7119b
Added switching TLE functionality as per #46

Added Switch TLE Functionality

---

src/leo-server-app/src/globals/globals.ts
src/leo-server-app/src/models/satellite.ts
src/leo-server-app/src/routes/satellite.ts
src/leo-server-app/src/tests/satellite.test.ts
src/leo-server-app/src/tests/schedule.test.ts

Changes made:
- Modified SatelliteModel schema to include noradId and tleLines fields
- Added global variable to store tleLines for satellites
- Added endpoint to update a satellite target's list of valid commands
- Refactored endpoints to use global tleLines variable
- Updated tests to support new changes

Feature: Satellite Endpoints Refactor

---

src/leo-client-app/package-lock.json
src/leo-server-app/src/app.ts
src/leo-server-app/src/routes/ping.ts

PR for issue #100 
need to add this on the server .env.local

Get response from mock server

---

src/docs/api/Satellite.md

Added the endpoint to Satellite.md

Updated Satellite.md

---

src/leo-server-app/src/models/log.ts
src/leo-server-app/src/routes/log.ts

Added a create log endpoint
added 2 get logs endpoints to get data based on commandId and scheduleId

New log endpoints

---

src/leo-server-app/src/app.ts
src/leo-server-app/src/models/satelliteUser.ts
src/leo-server-app/src/routes/satelliteUser.ts

Created new model for satellite users
added enpoints to create, get and edit records

Satellite users

---

src/leo-client-app/src/components/DetailedDisplay.tsx
src/leo-client-app/src/components/FuturePasses.tsx
src/leo-client-app/src/components/SatelliteInfo.tsx
src/leo-client-app/src/components/SatelliteTLE.tsx
src/leo-client-app/src/pages/detailed-display/[noradId]/[startTime]/[endTime].tsx
src/leo-client-app/src/pages/satellite-passes/index.tsx
src/leo-server-app/src/routes/satellite.ts
src/leo-server-app/src/utils/satellite.utils.ts

Changes made:
- Refactored frontend to dynamically fetch satellite information based on noradId
- Added helper methods to check for undefined tles
https://github.com/RishiVaya/Lower_Earth_Orbiters/assets/59628796/c3e6e402-3129-43db-abb2-a4170a2f5bd5

Fix: Fetching TLE Data

---

src/leo-server-app/src/jobs/schedule.job.ts
src/leo-server-app/src/routes/schedule.ts
src/leo-server-app/src/tests/satellite.test.ts
src/leo-server-app/src/utils/schedule.utils.ts

Changes made:
- Created an endpoint to execute a schedule for execution (direct execution)
- Created an endpoint to cancel a schedule during execution

Feature: Execute and Cancel Schedules

---

src/leo-server-app/src/models/user.ts
src/leo-server-app/src/routes/schedule.ts
src/leo-server-app/src/routes/user.ts

2 endpoints added
- getUserSatellites
- updateUserSatellites
changed log get endpoint for frontend

Satellites of interest

---

src/leo-client-app/src/components/Scheduler.tsx
src/leo-client-app/src/components/logs.tsx

Valid commands now show valid commands at user level
Also fixed `getLogs` endpoint to `getLogsBySatellite`

Connected valid commands per user

---

src/leo-client-app/src/components/Scheduler.tsx
src/leo-client-app/src/components/ViewScheduleCard.tsx
src/leo-client-app/src/components/operator-management/OperatorList.tsx
src/leo-client-app/src/constants/api.ts
src/leo-client-app/src/constants/hooks.ts
src/leo-server-app/src/routes/satelliteUser.ts
src/leo-server-app/src/routes/schedule.ts
src/leo-server-app/src/utils/schedule.utils.ts

Changes made:
- Added endpoint to batch create commands for schedule and integrated with frontend
- Made card to display queued commands
https://github.com/RishiVaya/Lower_Earth_Orbiters/assets/59628796/cf54fc8f-825d-4285-8b49-a1dbc3d0bd34

Feature: Create and Delete Commands from UI

---

src/leo-client-app/src/components/FuturePasses.tsx
src/leo-client-app/src/components/ViewScheduleCard.tsx
src/leo-server-app/src/routes/satellite.ts
src/leo-server-app/src/utils/satellite.utils.ts
src/leo-server-app/src/utils/schedule.utils.ts

Changes made:
- Ensure tleinfo is fetched

Fixed: Get Next Passes Call

---

src/docs/api/Satellite.md
src/leo-client-app/src/components/SatelliteName.tsx
src/leo-client-app/src/components/SatelliteTLE.tsx
src/leo-client-app/src/components/navbar/Navbar.tsx
src/leo-client-app/src/components/styles/component.css
src/leo-client-app/src/components/styles/futurePasses.css
src/leo-client-app/src/pages/satellite-passes/index.tsx
src/leo-server-app/src/globals/globals.ts
src/leo-server-app/src/routes/satellite.ts
src/leo-server-app/src/utils/satellite.utils.ts

https://github.com/RishiVaya/Lower_Earth_Orbiters/assets/35006641/8817aadf-1c59-4173-b7ae-e45507c34f4c
Display satellite name in a component, updates when it is changed. #164 
Currently a bit slow (not always as fast as video) due to multiple requests, should cut down in future pr
Also updated formatting so it looks better

Show name of satellite being displayed

---

src/leo-client-app/src/components/SatellitesOfInterest.tsx
src/leo-client-app/src/components/Scheduler.tsx
src/leo-client-app/src/components/UserName.tsx
src/leo-client-app/src/components/navbar/Navbar.tsx
src/leo-client-app/src/components/styles/component.css
src/leo-client-app/src/components/styles/satellitesOfInterest.css
src/leo-client-app/src/pages/index.tsx
src/leo-client-app/src/pages/satellite/[noradId].tsx
src/leo-client-app/src/pages/satellites-of-interest/index.tsx
src/leo-client-app/yarn.lock
src/leo-server-app/src/routes/user.ts

Demo:
https://github.com/LowerEarthOrbiters/Lower_Earth_Orbiters/assets/35006641/4fb70901-7448-4400-b797-82eff95ce3c5
Added satellites of interests page, and dynamically routed subsequent pages.
A bit of lag on name changing but itll be ok

Added Satellites of Interest Page

---

src/leo-server-app/package.json
src/leo-server-app/src/app.ts
src/leo-server-app/src/routes/satellite.ts
src/leo-server-app/src/server.ts
src/leo-server-app/src/utils/satellite.utils.ts

Changes made:
- Added script to run on prod
- Reference env files dynamically
- Set port number dynamically

feat: Backend deploy changes

---

src/leo-server-app/src/app.ts
src/leo-server-app/src/routes/satellite.ts
src/leo-server-app/src/utils/satellite.utils.ts

Changes made:
- Modified cors and updated env routing

fix: cors header bug

---

src/leo-server-app/src/app.ts
src/leo-server-app/src/models/command.ts
src/leo-server-app/src/utils/schedule.utils.ts

Changes made:
- Added command sequence timeout

feat: command sequence timeout

---

src/leo-client-app/src/components/logModal.tsx
src/leo-client-app/src/components/logs.tsx
src/leo-client-app/src/components/styles/logs.css
src/leo-client-app/src/pages/satellite-logs/index.tsx
src/leo-client-app/yarn.lock
src/leo-server-app/yarn.lock

Updated logs UI

---

src/leo-server-app/src/routes/satellite.ts
src/leo-server-app/src/routes/schedule.ts

changed get schedules filter to sort ascending by start time instead of create time

Schedule change

---

src/leo-server-app/src/routes/satelliteUser.ts
src/leo-server-app/src/tests/satelliteUser.test.ts

Added tests for all satellite User endpoints
fixed some of the endpoints

Sat user test

---

src/leo-server-app/src/routes/satellite.ts
src/leo-server-app/src/utils/satellite.utils.ts

added endpoint to get enxt passes by noradid and time for filtering

Satfilter endpoint

---

src/leo-client-app/src/components/Scheduler.tsx
src/leo-client-app/src/components/styles/Scheduler.css
src/leo-client-app/src/pages/edit-schedule/[satId]/[scheduleId].tsx
src/leo-server-app/src/routes/schedule.ts

right now by default there are no schedules because it takes it as current date, and there are no schedules in the db for the current date
https://github.com/LowerEarthOrbiters/Lower_Earth_Orbiters/assets/129548993/8fdb3d3d-57ad-40a8-862b-a4a357053fcb

Schedule filter

---

src/leo-client-app/src/components/EditSchedules.tsx
src/leo-client-app/src/components/Logs.tsx
src/leo-client-app/src/components/SatelliteInfo.tsx
src/leo-client-app/src/components/SatelliteName.tsx
src/leo-client-app/src/components/SatellitesOfInterest.tsx
src/leo-client-app/src/components/Scheduler.tsx
src/leo-client-app/src/components/UpcomingSchedules.tsx
src/leo-client-app/src/components/UserName.tsx
src/leo-client-app/src/components/navbar/Navbar.tsx
src/leo-client-app/src/components/styles/Scheduler.css
src/leo-client-app/src/components/styles/component.css
src/leo-client-app/src/components/styles/futurePasses.css
src/leo-client-app/src/constants/api.ts
src/leo-client-app/src/pages/edit-schedule/[satId]/[scheduleId].tsx
src/leo-client-app/src/pages/manage-operators/index.tsx
src/leo-client-app/src/pages/satellite-logs/[satId].tsx
src/leo-client-app/src/pages/satellite/[satId].tsx
src/leo-client-app/src/pages/satellites-of-interest/index.tsx
src/leo-client-app/src/pages/schedule-commands/[satId].tsx
src/leo-client-app/yarn.lock
src/leo-server-app/yarn.lock

Changed the schedules for specific satellite format to a table to improve readability. 
https://github.com/LowerEarthOrbiters/Lower_Earth_Orbiters/assets/23438377/b1eb9d3e-a7da-4dc9-96a0-44c35b8fdb93

Edit Schedules Cards

---

src/leo-client-app/src/components/EditSchedules.tsx
src/leo-client-app/src/components/Logs.tsx
src/leo-client-app/src/components/SatelliteInfo.tsx
src/leo-client-app/src/components/SatelliteName.tsx
src/leo-client-app/src/components/SatellitesOfInterest.tsx
src/leo-client-app/src/components/Scheduler.tsx
src/leo-client-app/src/components/UserName.tsx
src/leo-client-app/src/components/navbar/Navbar.tsx
src/leo-client-app/src/components/styles/Scheduler.css
src/leo-client-app/src/components/styles/component.css
src/leo-client-app/src/constants/api.ts
src/leo-client-app/src/pages/edit-schedule/[satId]/[scheduleId].tsx
src/leo-client-app/src/pages/manage-operators/index.tsx
src/leo-client-app/src/pages/satellite-logs/[satId].tsx
src/leo-client-app/src/pages/satellite/[satId].tsx
src/leo-client-app/src/pages/satellites-of-interest/index.tsx
src/leo-client-app/src/pages/schedule-commands/[satId].tsx
src/leo-client-app/yarn.lock
src/leo-server-app/yarn.lock

Allows the user to add a new satellite of interest with a user input of name and a valid unique noradID to track.
https://github.com/LowerEarthOrbiters/Lower_Earth_Orbiters/assets/23438377/075c00c0-e006-436b-8844-add337aac9f0

Add New Satellite of Interest

---

src/leo-client-app/src/components/Scheduler.tsx
src/leo-client-app/src/components/UpcomingSchedules.tsx

https://github.com/LowerEarthOrbiters/Lower_Earth_Orbiters/assets/129548993/c20e7e6d-9696-4f7f-9a84-7b65057fde84

Overpass filter

---

src/leo-server-app/src/app.ts
src/leo-server-app/src/server.ts
src/leo-server-app/src/socket.ts

Changes made:
- Added support for encrypted socket connection
- Separated ports for socket and http connections

Refactor: Separate socket and http requests

---

src/leo-server-app/src/routes/user.ts

Changes made:
- /users/getUserByEmail lets you fetch user record by email

feat: Added endpoint to fetch user by email

---

src/leo-client-app/src/app/api/auth/[auth0]/user.ts
src/leo-client-app/src/components/SatellitesOfInterest.tsx
src/leo-client-app/src/components/UserName.tsx
src/leo-client-app/src/pages/satellites-of-interest/index.tsx
src/leo-server-app/.gitignore
src/leo-server-app/src/socket.ts

https://github.com/smiths/capTemplate/assets/35006641/df2128b2-d6ad-4df2-8fa3-f8d6a466a2db
Dynamically routed users via auth-0, showing different satellites per users as per mongoDB record.
#214

Dynamically routed users via auth-0

---

src/leo-client-app/src/components/SatelliteCommands.tsx
src/leo-client-app/src/components/navbar/Navbar.tsx
src/leo-client-app/src/components/styles/satelliteCommands.css
src/leo-client-app/src/pages/satellite-commands/[satId].tsx
src/leo-client-app/src/pages/satellite-logs/[satId].tsx

added a page to edit, remove and add commands to a satellite
https://github.com/LowerEarthOrbiters/Lower_Earth_Orbiters/assets/129548993/9f8773c0-97d3-40a1-b53b-9b446c8e546a

Added page for Satellite Commands
